-- @file cleanup.sql
-- @author Andrew D. Zonenberg
-- @brief Deletes pretty much all content from the database and recreates table structure.
-- You almost certainly do NOT want to use this in a production environment!
